### ISSUE TITLE
Fehler beim Zugriff auf die Datenbank (money_details)

### ISSUE THREAD

**Issue by RMajewski** [RMajewski/haushaltsbuch#66]
Hier die Fehlerausgabe:

	java.sql.SQLException: ResultSet closed
		at org.sqlite.core.CoreResultSet.checkOpen(CoreResultSet.java:69)
		at org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:38)
		at org.sqlite.jdbc3.JDBC3ResultSet.getString(JDBC3ResultSet.java:437)
		at haushaltsbuch.tables.models.MoneyDetailsListModel.searchName(MoneyDetailsListModel.java:73)
		at haushaltsbuch.tables.models.MoneyDetailsListModel.getValueAt(MoneyDetailsListModel.java:137)
		at javax.swing.JTable.getValueAt(JTable.java:2717)
		at javax.swing.JTable.prepareRenderer(JTable.java:5719)
		at javax.swing.plaf.basic.BasicTableUI.paintCell(BasicTableUI.java:2108)
		at javax.swing.plaf.basic.BasicTableUI.paintCells(BasicTableUI.java:2010)
		at javax.swing.plaf.basic.BasicTableUI.paint(BasicTableUI.java:1806)
		at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
		at javax.swing.JComponent.paintComponent(JComponent.java:770)
		at javax.swing.JComponent.paint(JComponent.java:1046)
		at javax.swing.JComponent.paintChildren(JComponent.java:879)
		at javax.swing.JComponent.paint(JComponent.java:1055)
		at javax.swing.JViewport.paint(JViewport.java:731)
		at javax.swing.JComponent.paintChildren(JComponent.java:879)
		at javax.swing.JComponent.paint(JComponent.java:1055)
		at javax.swing.JComponent.paintChildren(JComponent.java:879)
		at javax.swing.JComponent.paint(JComponent.java:1055)
		at javax.swing.JComponent.paintChildren(JComponent.java:879)
		at javax.swing.JComponent.paint(JComponent.java:1055)
		at javax.swing.JLayeredPane.paint(JLayeredPane.java:585)
		at javax.swing.JComponent.paintChildren(JComponent.java:879)
		at javax.swing.JComponent.paint(JComponent.java:1055)
		at javax.swing.JComponent.paintChildren(JComponent.java:879)
		at javax.swing.JComponent.paint(JComponent.java:1055)
		at javax.swing.JComponent.paintChildren(JComponent.java:879)
		at javax.swing.JComponent.paint(JComponent.java:1055)
		at javax.swing.JLayeredPane.paint(JLayeredPane.java:585)
		at javax.swing.JComponent.paintToOffscreen(JComponent.java:5223)
		at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:295)
		at javax.swing.RepaintManager.paint(RepaintManager.java:1249)
		at javax.swing.JComponent._paintImmediately(JComponent.java:5171)
		at javax.swing.JComponent.paintImmediately(JComponent.java:4982)
		at javax.swing.RepaintManager$3.run(RepaintManager.java:808)
		at javax.swing.RepaintManager$3.run(RepaintManager.java:796)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
		at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:796)
		at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:769)
		at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:718)
		at javax.swing.RepaintManager.access$1100(RepaintManager.java:62)
		at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1677)
		at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
		at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
		at java.awt.EventQueue.access$300(EventQueue.java:103)
		at java.awt.EventQueue$3.run(EventQueue.java:706)
		at java.awt.EventQueue$3.run(EventQueue.java:704)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
		at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
		at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
		at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
		at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
		at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
		at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
		at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by RMajewski** [comment]
Fehler wird ausgelöst, wenn zuvor die Kategorie oder das Geschäft gelöscht wurde. Dann kann der Name nicht gefunden werden und somit wird der Fehler ausgelöst.
